[FE] Feat: 기록 상세페이지 patch (#205)
* Fix: 로그인 실패 시에도 성공으로 인식되는 오류 해결 (#165) (#166)

- 실패 시 null return
- signup 시, id와 비밀번호를 콘솔에 출력하던 코드 제거

* Fix: 이메일 유효성 검증 방식 변경 (#169) (#171)

- `asdf@asdfasdfasdf`와 같은 형식의 이메일이 통과되는 버그 해결
- `.xx`와 같이 최소 두 글자 이상의 문자열이 `.` 다음에 따라와야 유효성 검증 통과

* [FE] Feat: 비밀번호 찾기 기능 (#175)

* Feat: 레이아웃 및 기본 로직 구성 (#150)

todo
- api 연결
- TempPasswordSent 컴포넌트 레이아웃 구성
- TempPasswordSent에서 로그인 페이지로 연결

* Feat: 컴포넌트 선택적 렌더링을 위한 state 추가 (#150)

- TempPasswordSent 추가

* Feat: 비밀번호 찾기 기능 구현 (#150)

* Fix: signIn 요청에 대한 응답 형식 변경 (#176) (#182)

- 객체 형태(status, memberId)로 변경

* Feat: 회원 탈퇴 기능 구현 (#183) (#185)

- 비로그인 시 로그인 페이지로 리다이렉트

* [FE] Feat: 헤더 컴포넌트 (#187)

* Feat: 헤더 컴포넌트 구현 (#172)

* Chore: types/node 설치 및 vite.config 파일 수정 (#172)

- ngrok 주소가 계속 변경되어 merge conflict이 발생하는 문제 해결을 위해
  proxy 주소를 환경변수로 재설정

* [FE] Feat: 기록 리스트 API 연결 (#188)

* Feat: type alias 들을 types/History.ts 파일로 뺌 (#161)

dependency cycle detected 에러 때문에 History의 data type들을 외부에서 따로 관리함

* Feat: History List 최신순 보기의 무한 스크롤 구현 (#161)

useInfiniteQuery 로 10개씩 무한 스크롤 구현

* Feat: 월별보기 토글 클릭시 기록이 있는 날의 날짜 밑에 표시된 달력 조회 (#161)

월별보기 토글 클릭시 (기록이 없어도) 이번달 달력부터 조회
지난/다음 달 이동시 산책 기록이 표시되어 있는 달력 조회
해당 달의 기록 목록 조회는 아직 미구현

* Formatting: 달력에 표시되는 기록들 날짜 조회 API 이름 변경 (#161)

함수 이름 getHistoryMonthList 은 해당 달의 기록들만 조회할 때 사용하기 위해서
getHistoryCalendarList 로 이름 변경

* Feat: 달력 토글 선택시 전체 기록 중 해당 달의 기록만 10개씩 조회 (#161)

ToDo
- 무한스크롤 시 화면 제일 상단으로 가는 문제 해결 필요

* Refactor: 월별보기 토글 클릭 useEffect → reactQuery (#161)

queryKey에 state 를 넣으면
date 의 state 변경될 때마다 api 재요청된다는 걸 알게 돼서 reactQuery로 변경

* Feat: 달력에서 날짜 선택하면 해당 날짜의 기록만 조회 (#161)

useInfiniteQuery의 queryKey에는 관리되어야 할 state 들만 넣고 쓸데없는 queryKey 정리

* Fix: 다음 페이지 로딩 후 전체 렌더링 → 스크롤 맨 위로 가는 거 고침 (#161)

isFetchingNextPage 가 true 면 <p>로딩 중</p>, 끝나면 데이터 받아오는데,
isFetchingNextPage를
전체 <div> 보다 위에 놔서 로딩 될 때마다 전체 페이지 새로고침 돼서 스크롤이 맨 위로 올라감
→ 마지막 데이터(History) 밑에  isFetchingNextPage 를 둬서 고침

* Design: history 시간 표시 옆 시계 아이콘 추가 (#161)

* Design: history 시간 표시 옆 시계 아이콘 추가 (#161)

* Fix: 순간기록(snapForm) textarea의 defaultValue  (#136)

textarea의 defaultValue에 initial Text가
null 이면 ''(공백)
null 이 아니면 initial Text 가 들어가도록
defaultValue에 null 이 들어갈 수도 있어서 발생하는 type 에러 고침

* Feat: 걷기기록 메세지, 공개 설정 변경 (#136)

Todo
- 타입 에러 fix 필요
- enum 공부해서 적용 필요
- drop down 로직 drop down 컴포넌츠 안으로 숨기기

* Feat: 순간기록(HistoryItem) 수정 기능 구현 (#136)

Todo 타입 에러 fix 필요

* Fix: mutationFn 파라미터의 기본타입(void)과 타입 충돌 해결 (#136)

useMutate<TData, TError, TVariables, TContext>()
TData: mutationFn에서 반환되는 data의 타입
TError: 리턴되는 에러 타입
TVariables: mutationFn의 파라미터 타입
TContext: mutationFn이 실행되기 전 onMutate 에서 반환되는 context의 타입

* Fix: image 없으면 null을 append하지 않도록 해결 (#136)

if(image) 인 경우에만 formData에 append 하도록 조건문 추가

---------

Co-authored-by: hajongon <114554291+hajongon@users.noreply.github.com>